name: Tests
on: push

jobs:
  test:

    runs-on: "ubuntu-latest"
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest -vvv

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          config-file: ./.github/codeql.yml
          queries: +security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
